In [1]:
import numpy as np
import matplotlib
import random

In [2]:
F18 = open('F19FitnessAverageFinal2.1.txt', 'r').readlines()

In [3]:
IM = 0
OSM= 0
KommaS = 0
PlusS = 0
IR = 0
DR = 0
GIR = 0
GDR = 0
IS001 = 0
IS005 = 0
IS01 = 0
NP2 = 0
NP5 = 0
NP10 = 0
NP20 = 0
NO2 = 0
NO5 = 0
NO10 = 0
NO20 = 0

IM2 = 0
OSM2= 0
KommaS2 = 0
PlusS2 = 0
IR2 = 0
DR2 = 0
GIR2 = 0
GDR2 = 0
IS0012 = 0
IS0052 = 0
IS012 = 0
NP22 = 0
NP52 = 0
NP102 = 0
NP202 = 0
NO22 = 0
NO52 = 0
NO102 = 0
NO202 = 0

In [4]:

Fitness = np.zeros((112, 8))
# [0.01, 0.05, 0.1]: sigma
# [2, 5, 10, 20]: parents
# [2,5, 10,20]: offspring
Average = np.zeros(19)
Average2 = np.zeros(19)
for idx, x in enumerate(F18):
    y = x.split()
    if y[1] == 'IM':
        Fitness[idx][0] = 1
        IM += float(y[10])
        IM2 += 1
        Average[0] += float(y[10])
        Average2[0] += 1
    if y[1] == 'OSM':
        Fitness[idx][0] = 2
        OSM += float(y[10])
        OSM2 += 1
        Average[1] += float(y[10])
        Average2[1] += 1
    if y[2] == 'KommaS':
        Fitness[idx][1] = 1
        KommaS += float(y[10])
        KommaS2 += 1
        Average[2] += float(y[10])
        Average2[2] += 1
    if y[2] == 'PlusS':
        Fitness[idx][1] = 2
        PlusS += float(y[10])
        PlusS2 += 1
        Average[3] += float(y[10])
        Average2[3] += 1
    if y[3] == 'IR':
        Fitness[idx][2] = 1
        IR += float(y[10])
        IR2 += 1
        Average[4] += float(y[10])
        Average2[4] += 1
    if y[3] == 'DR':
        Fitness[idx][2] = 2
        DR += float(y[10])
        DR2 += 1
        Average[5] += float(y[10])
        Average2[5] += 1
    if y[3] == 'GIR':
        Fitness[idx][2] = 3
        GIR += float(y[10])
        GIR += 1
        Average[6] += float(y[10])
        Average2[6] += 1
    if y[3] == 'GDR':
        Fitness[idx][2] = 4
        GDR += float(y[10])
        GDR2 += 1
        Average[7] += float(y[10])
        Average2[7] += 1


    IS = float(y[5])
    Fitness[idx][3] = IS
    if IS ==  0.01:
        IS001 += float(y[10])
        IS0012 += 1
        Average[8] += float(y[10])
        Average2[8] += 1
    if IS == 0.05:
        IS005 += float(y[10])
        IS0052 += 1
        Average[9] += float(y[10])
        Average2[9] += 1
    if IS == 0.1:
        IS01 += float(y[10])
        IS012 += 1
        Average[10] += float(y[10])
        Average2[10] += 1




    NP = int(y[7])
    Fitness[idx][4] = NP
    # if NP ==  2:
    #     NP2 += float(y[10])
    #     NP22 += 1
    #     Average[11] += float(y[10])
    #     Average2[11] += 1
    # if NP == 5:
    #     NP5 += float(y[10])
    #     NP52 += 1
    #     Average[12] += float(y[10])
    #     Average2[12] += 1
    # if NP == 10:
    #     NP10 += float(y[10])
    #     NP102 += 1
    #     Average[13] += float(y[10])
    #     Average2[13] += 1
    # if NP == 20:
    #     NP20 += float(y[10])
    #     NP202 += 1
    #     Average[14] += float(y[10])
    #     Average2[14] += 1
    p = ''
    for letter in y[9]:
        if letter != ':':
            p = p + letter
    Fitness[idx][5] = int(p)
    NO = int(p)
    if NO ==  2:
        NO2 += float(y[10])
        NO22 += 1
        Average[15] += float(y[10])
        Average2[15] += 1
    if NO == 5:
        NO5 += float(y[10])
        NO52 += 1
        Average[16] += float(y[10])
        Average2[16] += 1
    if NO == 10:
        NO10 += float(y[10])
        NO102 += 1
        Average[17] += float(y[10])
        Average2[17] += 1
    if NO == 20:
        NO20 += float(y[10])
        NO202 += 1
        Average[18] += float(y[10])
        Average2[18] += 1
    Fitness[idx][6] = float(y[10])
    Fitness[idx][7] = float(y[11])
    

In [5]:
print(Fitness)

[[ 2.   1.   1.   0.1  2.  14.  40.1 46. ]
 [ 2.   1.   1.   0.1  4.  28.  40.4 44. ]
 [ 2.   1.   1.   0.1  6.  42.  40.7 46. ]
 [ 2.   1.   1.   0.1  8.  56.  41.8 44. ]
 [ 2.   1.   1.   0.1 10.  70.  41.5 44. ]
 [ 2.   1.   1.   0.1 12.  84.  42.6 48. ]
 [ 2.   1.   1.   0.1 14.  98.  42.5 44. ]
 [ 2.   1.   2.   0.1  2.  14.  42.9 48. ]
 [ 2.   1.   2.   0.1  4.  28.  42.8 46. ]
 [ 2.   1.   2.   0.1  6.  42.  42.8 46. ]
 [ 2.   1.   2.   0.1  8.  56.  43.8 46. ]
 [ 2.   1.   2.   0.1 10.  70.  43.9 48. ]
 [ 2.   1.   2.   0.1 12.  84.  44.6 46. ]
 [ 2.   1.   2.   0.1 14.  98.  44.9 48. ]
 [ 2.   1.   3.   0.1  2.  14.  39.5 44. ]
 [ 2.   1.   3.   0.1  4.  28.  40.6 44. ]
 [ 2.   1.   3.   0.1  6.  42.  40.9 46. ]
 [ 2.   1.   3.   0.1  8.  56.  41.7 46. ]
 [ 2.   1.   3.   0.1 10.  70.  41.7 46. ]
 [ 2.   1.   3.   0.1 12.  84.  42.4 46. ]
 [ 2.   1.   3.   0.1 14.  98.  43.  48. ]
 [ 2.   1.   4.   0.1  2.  14.  42.1 46. ]
 [ 2.   1.   4.   0.1  4.  28.  43.9 48. ]
 [ 2.   1. 

In [8]:
F_opt = 0
X_opt = None
for entry in Fitness:
    if entry[-2]  > F_opt:
        F_opt = entry[-2]
        X_opt = entry

Fitness_sort = Fitness[Fitness[:, -2].argsort()]
print('The top combinations by average are:')
print(Fitness_sort[-3:])
print('The bottom combinations by average are:')
print(Fitness_sort[:3])

print('Index of top values 3:')
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-1][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-2][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-3][-2]))

print('Index of bottom values 3:')
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-1][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-2][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-3][-2]))

The top combinations by average are:
[[ 1.   1.   2.   0.1 14.  98.  45.9 48. ]
 [ 1.   2.   4.   0.1 14.  98.  45.9 48. ]
 [ 1.   2.   2.   0.1 14.  98.  46.  48. ]]
The bottom combinations by average are:
[[ 2.   2.   3.   0.1  2.  14.  36.4 40. ]
 [ 2.   2.   1.   0.1  2.  14.  36.5 42. ]
 [ 2.   2.   4.   0.1  2.  14.  38.  42. ]]
Index of top values 3:
(array([97], dtype=int64),)
(array([ 69, 111], dtype=int64),)
(array([ 69, 111], dtype=int64),)
Index of bottom values 3:
(array([49], dtype=int64),)
(array([28], dtype=int64),)
(array([42], dtype=int64),)


In [9]:
Fitness_sort = Fitness[Fitness[:, -1].argsort()]
print('The top combinations by top value are:')
print(Fitness_sort[-3:])

print('Index of top values 3:')
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-1][-1]))
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-2][-1]))
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-3][-1]))

The top combinations by top value are:
[[ 1.   2.   4.   0.1 14.  98.  45.9 48. ]
 [ 1.   1.   2.   0.1 12.  84.  45.6 50. ]
 [ 1.   2.   2.   0.1 12.  84.  45.  50. ]]
Index of top values 3:
(array([68, 96], dtype=int64),)
(array([68, 96], dtype=int64),)
(array([  5,   7,  11,  13,  20,  22,  23,  24,  25,  26,  27,  33,  38,
        40,  41,  51,  52,  53,  54,  55,  59,  60,  61,  62,  65,  66,
        67,  69,  71,  72,  73,  75,  76,  80,  81,  83,  86,  87,  88,
        89,  90,  92,  93,  94,  95,  97, 100, 101, 102, 103, 107, 108,
       109, 110, 111], dtype=int64),)
