In [355]:
import numpy as np
import matplotlib
import random

In [356]:
F18 = open('F18FitnessAverageFinal2.1.txt', 'r').readlines()

In [357]:
IM = 0
OSM= 0
KommaS = 0
PlusS = 0
IR = 0
DR = 0
GIR = 0
GDR = 0
IS001 = 0
IS005 = 0
IS01 = 0
NP2 = 0
NP5 = 0
NP10 = 0
NP20 = 0
NO2 = 0
NO5 = 0
NO10 = 0
NO20 = 0

IM2 = 0
OSM2= 0
KommaS2 = 0
PlusS2 = 0
IR2 = 0
DR2 = 0
GIR2 = 0
GDR2 = 0
IS0012 = 0
IS0052 = 0
IS012 = 0
NP22 = 0
NP52 = 0
NP102 = 0
NP202 = 0
NO22 = 0
NO52 = 0
NO102 = 0
NO202 = 0

In [363]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [367]:

Fitness = np.zeros((112, 8))
# [0.01, 0.05, 0.1]: sigma
# [2, 5, 10, 20]: parents
# [2,5, 10,20]: offspring
Average = np.zeros(19)
Average2 = np.zeros(19)
for idx, x in enumerate(F18):
    y = x.split()
    if y[1] == 'IM':
        Fitness[idx][0] = 1
        IM += float(y[10])
        IM2 += 1
        Average[0] += float(y[10])
        Average2[0] += 1
    if y[1] == 'OSM':
        Fitness[idx][0] = 2
        OSM += float(y[10])
        OSM2 += 1
        Average[1] += float(y[10])
        Average2[1] += 1
    if y[2] == 'KommaS':
        Fitness[idx][1] = 1
        KommaS += float(y[10])
        KommaS2 += 1
        Average[2] += float(y[10])
        Average2[2] += 1
    if y[2] == 'PlusS':
        Fitness[idx][1] = 2
        PlusS += float(y[10])
        PlusS2 += 1
        Average[3] += float(y[10])
        Average2[3] += 1
    if y[3] == 'IR':
        Fitness[idx][2] = 1
        IR += float(y[10])
        IR2 += 1
        Average[4] += float(y[10])
        Average2[4] += 1
    if y[3] == 'DR':
        Fitness[idx][2] = 2
        DR += float(y[10])
        DR2 += 1
        Average[5] += float(y[10])
        Average2[5] += 1
    if y[3] == 'GIR':
        Fitness[idx][2] = 3
        GIR += float(y[10])
        GIR += 1
        Average[6] += float(y[10])
        Average2[6] += 1
    if y[3] == 'GDR':
        Fitness[idx][2] = 4
        GDR += float(y[10])
        GDR2 += 1
        Average[7] += float(y[10])
        Average2[7] += 1


    IS = float(y[5])
    Fitness[idx][3] = IS
    if IS ==  0.01:
        IS001 += float(y[10])
        IS0012 += 1
        Average[8] += float(y[10])
        Average2[8] += 1
    if IS == 0.05:
        IS005 += float(y[10])
        IS0052 += 1
        Average[9] += float(y[10])
        Average2[9] += 1
    if IS == 0.1:
        IS01 += float(y[10])
        IS012 += 1
        Average[10] += float(y[10])
        Average2[10] += 1




    NP = int(y[7])
    Fitness[idx][4] = NP
    # if NP ==  2:
    #     NP2 += float(y[10])
    #     NP22 += 1
    #     Average[11] += float(y[10])
    #     Average2[11] += 1
    # if NP == 5:
    #     NP5 += float(y[10])
    #     NP52 += 1
    #     Average[12] += float(y[10])
    #     Average2[12] += 1
    # if NP == 10:
    #     NP10 += float(y[10])
    #     NP102 += 1
    #     Average[13] += float(y[10])
    #     Average2[13] += 1
    # if NP == 20:
    #     NP20 += float(y[10])
    #     NP202 += 1
    #     Average[14] += float(y[10])
    #     Average2[14] += 1
    p = ''
    for letter in y[9]:
        if letter != ':':
            p = p + letter
    Fitness[idx][5] = int(p)
    NO = int(p)
    if NO ==  2:
        NO2 += float(y[10])
        NO22 += 1
        Average[15] += float(y[10])
        Average2[15] += 1
    if NO == 5:
        NO5 += float(y[10])
        NO52 += 1
        Average[16] += float(y[10])
        Average2[16] += 1
    if NO == 10:
        NO10 += float(y[10])
        NO102 += 1
        Average[17] += float(y[10])
        Average2[17] += 1
    if NO == 20:
        NO20 += float(y[10])
        NO202 += 1
        Average[18] += float(y[10])
        Average2[18] += 1
    Fitness[idx][6] = float(y[10])
    Fitness[idx][7] = float(y[11])
    

In [368]:
print(Fitness)

[[ 2.          1.          1.          0.1         2.         14.
   3.09311201  4.32525952]
 [ 2.          1.          1.          0.1         4.         28.
   3.10104801  3.894081  ]
 [ 2.          1.          1.          0.1         6.         42.
   3.20447834  3.99361022]
 [ 2.          1.          1.          0.1         8.         56.
   3.46009999  4.71698113]
 [ 2.          1.          1.          0.1        10.         70.
   3.47282352  4.44839858]
 [ 2.          1.          1.          0.1        12.         84.
   3.53130707  4.57875458]
 [ 2.          1.          1.          0.1        14.         98.
   3.31089499  3.7993921 ]
 [ 2.          1.          2.          0.1         2.         14.
   3.40969587  4.09836066]
 [ 2.          1.          2.          0.1         4.         28.
   3.36317779  4.32525952]
 [ 2.          1.          2.          0.1         6.         42.
   3.48734109  4.57875458]
 [ 2.          1.          2.          0.1         8.         56.
   3

In [395]:
F_opt = 0
X_opt = None
for entry in Fitness:
    if entry[-2]  > F_opt:
        F_opt = entry[-2]
        X_opt = entry

Fitness_sort = Fitness[Fitness[:, -2].argsort()]
print('The top combinations by average are:')
print(Fitness_sort[-3:])
print('The bottom combinations by average are:')
print(Fitness_sort[:3])

print('Index of top values 3:')
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-1][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-2][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[-3:][-3][-2]))

print('Index of bottom values 3:')
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-1][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-2][-2]))
print(np.where(Fitness[:, -2] == Fitness_sort[:3][-3][-2]))


The top combinations by average are:
[[ 1.          2.          4.          0.1         6.         42.
   3.82683136  4.86381323]
 [ 1.          2.          1.          0.1        10.         70.
   3.87110251  4.44839858]
 [ 1.          2.          2.          0.1         8.         56.
   3.96864889  4.71698113]]
The bottom combinations by average are:
[[ 1.          2.          4.          0.1        14.         98.
   2.78705953  3.24675325]
 [ 2.          2.          4.          0.1        14.         98.
   2.79590304  3.54107649]
 [ 2.          2.          2.          0.1         2.         14.
   2.96162453  3.70919881]]
Index of top values 3:
(array([94], dtype=int64),)
(array([88], dtype=int64),)
(array([107], dtype=int64),)
Index of bottom values 3:
(array([35], dtype=int64),)
(array([55], dtype=int64),)
(array([111], dtype=int64),)


In [399]:
Fitness_sort = Fitness[Fitness[:, -1].argsort()]
print('The top combinations by top value are:')
print(Fitness_sort[-3:])

print('Index of top values 3:')
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-1][-1]))
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-2][-1]))
print(np.where(Fitness[:, -1] == Fitness_sort[-3:][-3][-1]))


The top combinations by top value are:
[[ 2.          1.          4.          0.1         6.         42.
   3.45456196  5.18672199]
 [ 1.          2.          4.          0.1         8.         56.
   3.6915311   5.36480687]
 [ 2.          1.          3.          0.1         2.         14.
   3.19509828  5.55555556]]
Index of top values 3:
(array([14], dtype=int64),)
(array([108], dtype=int64),)
(array([ 23,  24,  90,  98, 102], dtype=int64),)


In [ ]:
import pandas as pd

# Assuming ea_data is your original DataFrame
ea_data = pd.read_csv("results-test-ea.csv")

# Filter F18_data and F19_data
F18_data = ea_data.query('problem=="F18"').copy()
F19_data = ea_data.query('problem=="F19"').copy()

# Identify the top 3 and bottom 3 rows based on average_fitness
top3_F18 = F18_data.nlargest(3, 'average_fitness')
bottom3_F18 = F18_data.nsmallest(3, 'average_fitness')

top3_F19 = F19_data.nlargest(3, 'average_fitness')
bottom3_F19 = F19_data.nsmallest(3, 'average_fitness')

# Save results to CSV files
print(top3_F18)
print(bottom3_F18)

print(top3_F19)
print(bottom3_F19)

# Replace values in the crossover, mutation, and selection columns
F18_data['crossover'] = F18_data['crossover'].replace({'uniform_crossover': 'UC', 'k_point_crossover': 'OPC'})
F18_data['mutation'] = F18_data['mutation'].replace({'uniform_mutation': 'UM', 'bit_flip_mutation': 'BFM'})
F18_data['selection'] = F18_data['selection'].replace({'tournament_mating_seletion': 'TS', 'roulette_mating_selection': 'RS'})

F19_data['crossover'] = F19_data['crossover'].replace({'uniform_crossover': 'UC', 'k_point_crossover': 'OPC'})
F19_data['mutation'] = F19_data['mutation'].replace({'uniform_mutation': 'UM', 'bit_flip_mutation': 'BFM'})
F19_data['selection'] = F19_data['selection'].replace({'tournament_mating_seletion': 'TS', 'roulette_mating_selection': 'RS'})

# Define a function to combine columns
def combine_columns(row):
    return f"{row['crossover']}-{row['mutation']}-{row['selection']}"

# Adding a new combined column for F18_data and F19_data
F18_data['classifier_name'] = F18_data.apply(lambda row: combine_columns(row), axis=1)
F19_data['classifier_name'] = F19_data.apply(lambda row: combine_columns(row), axis=1)

# Add a new column 'dataset_name' with unique values for each row
F18_data['dataset_name'] = 'Dataset_' + (F18_data.groupby('classifier_name').cumcount() + 1).astype(str)
F19_data['dataset_name'] = 'Dataset_' + (F19_data.groupby('classifier_name').cumcount() + 1).astype(str)

# Rename 'best_fitness' to 'accuracy'
F18_data = F18_data.rename(columns={'best_fitness': 'accuracy'})
F19_data = F19_data.rename(columns={'best_fitness': 'accuracy'})

# Create new DataFrames with columns in the desired order
F18_result = F18_data[['classifier_name', 'dataset_name', 'accuracy']]
F19_result = F19_data[['classifier_name', 'dataset_name', 'accuracy']]

# Save results to CSV files
F18_result.to_csv('F18_result-test.csv', index=False)
F19_result.to_csv('F19_results-test.csv', index=False)